"""Wallet-level intelligence: wash-trading detection and smart-money scoring.

GeckoTerminal's ``trades`` endpoint returns the wallet behind every swap, which
makes wallet-level analysis available without a paid data provider. Two
questions matter for trading decisions:

**Is this volume real?** Wash trading is cheap on Solana and specifically
targets the volume and transaction-count filters that naive bots screen on. The
signature is unmistakable once you look at per-wallet profiles rather than
aggregates: a cohort of wallets, each trading only this token, each with a
near-identical number of buys and sells, each cycling a similar notional. Real
retail flow is ragged — most wallets buy once and never return, a few trade
repeatedly, sizes vary over orders of magnitude. Manufactured flow is
suspiciously uniform, because it is generated by one script.

**Who is buying?** A wallet that repeatedly enters tokens that subsequently rise
is worth following. The hard part is separating skill from luck and from
insiders: with thousands of wallets, some will look brilliant by chance. The
scoring here requires a minimum track record and reports a confidence interval
rather than a point estimate, so the caller can tell "good" from "not yet
known".
"""

from __future__ import annotations

import logging
import math
import statistics
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Sequence

log = logging.getLogger(__name__)


@dataclass
class WalletProfile:
    """Aggregate behaviour of one wallet within a single pool."""

    wallet: str
    buys: int = 0
    sells: int = 0
    volume_usd: float = 0.0
    first_ts: int = 0
    last_ts: int = 0
    sizes: list[float] = field(default_factory=list)

    @property
    def trades(self) -> int:
        return self.buys + self.sells

    @property
    def round_trip_ratio(self) -> float:
        """How balanced buys and sells are. Near 1.0 means the wallet ends flat,
        which for a high-trade-count wallet is the signature of cycling rather
        than investing."""
        if self.buys == 0:
            return 0.0
        return min(self.sells / self.buys, self.buys / max(self.sells, 1))

    @property
    def duration_min(self) -> float:
        return max(0.0, (self.last_ts - self.first_ts) / 60.0)

    @property
    def size_cv(self) -> float:
        """Coefficient of variation of trade sizes. Human flow is highly
        dispersed; scripted flow is not."""
        if len(self.sizes) < 2:
            return 0.0
        mean = statistics.fmean(self.sizes)
        if mean <= 0:
            return 0.0
        return statistics.pstdev(self.sizes) / mean


@dataclass
class WashReport:
    """Verdict on whether a pool's activity looks manufactured."""

    pool: str
    n_wallets: int
    n_trades: int
    wash_score: float                 # 0 (organic) .. 1 (clearly manufactured)
    suspect_wallets: list[str] = field(default_factory=list)
    suspect_volume_share: float = 0.0
    signals: dict[str, float] = field(default_factory=dict)
    reasons: list[str] = field(default_factory=list)

    @property
    def is_suspicious(self) -> bool:
        return self.wash_score >= 0.5

    def adjusted_volume(self, reported_volume_usd: float) -> float:
        """Reported volume with the suspect share removed.

        Downstream features should use this rather than the raw figure, since
        the whole point of wash trading is to make the raw figure lie.
        """
        return max(0.0, reported_volume_usd * (1.0 - self.suspect_volume_share))


def profile_wallets(trades: Sequence[Any]) -> dict[str, WalletProfile]:
    """Build per-wallet profiles from a pool's swap history."""
    profiles: dict[str, WalletProfile] = {}
    for t in trades:
        wallet = _get(t, "wallet", "")
        if not wallet:
            continue
        ts = _ts(t)
        prof = profiles.get(wallet)
        if prof is None:
            prof = WalletProfile(wallet=wallet, first_ts=ts, last_ts=ts)
            profiles[wallet] = prof
        vol = float(_get(t, "volume_usd", 0.0) or 0.0)
        if str(_get(t, "kind", "")) == "buy":
            prof.buys += 1
        else:
            prof.sells += 1
        prof.volume_usd += vol
        prof.sizes.append(vol)
        prof.first_ts = min(prof.first_ts, ts) if prof.first_ts else ts
        prof.last_ts = max(prof.last_ts, ts)
    return profiles


def detect_wash_trading(
    pool: str,
    trades: Sequence[Any],
    *,
    min_trades_for_suspicion: int = 8,
    uniformity_tolerance: float = 0.25,
) -> WashReport:
    """Score how much of a pool's activity looks manufactured.

    Four independent signals are combined. Each is scaled to 0–1 and they are
    averaged with weights reflecting how hard each is to fake accidentally.
    """
    profiles = profile_wallets(trades)
    n_trades = sum(p.trades for p in profiles.values())
    report = WashReport(pool=pool, n_wallets=len(profiles), n_trades=n_trades, wash_score=0.0)
    if len(profiles) < 3 or n_trades < 10:
        report.reasons.append("too little activity to judge")
        return report

    total_volume = sum(p.volume_usd for p in profiles.values()) or 1.0
    heavy = [p for p in profiles.values() if p.trades >= min_trades_for_suspicion]

    # --- signal 1: cohort uniformity -------------------------------------
    # Wallets generated by one script share a trade count. Real traders do not.
    uniformity = 0.0
    cohort: list[WalletProfile] = []
    if len(heavy) >= 3:
        counts = [p.trades for p in heavy]
        median_count = statistics.median(counts)
        if median_count > 0:
            cohort = [
                p for p in heavy
                if abs(p.trades - median_count) / median_count <= uniformity_tolerance
            ]
            uniformity = len(cohort) / len(heavy)
            if len(cohort) >= 3:
                report.reasons.append(
                    f"{len(cohort)} wallets cluster around {median_count:.0f} trades each"
                )

    # --- signal 2: round-tripping ----------------------------------------
    # A high-activity wallet that ends flat was cycling, not accumulating.
    rt_scores = [p.round_trip_ratio for p in heavy]
    round_tripping = statistics.fmean(rt_scores) if rt_scores else 0.0
    if round_tripping > 0.7 and len(heavy) >= 3:
        report.reasons.append(f"active wallets end near-flat (mean balance {round_tripping:.2f})")

    # --- signal 3: size uniformity ---------------------------------------
    # Organic trade sizes vary by orders of magnitude; scripted ones do not.
    cvs = [p.size_cv for p in heavy if len(p.sizes) >= 3]
    size_uniformity = 0.0
    if cvs:
        mean_cv = statistics.fmean(cvs)
        # CV below ~0.6 is implausibly regular for retail flow.
        size_uniformity = max(0.0, min(1.0, (0.6 - mean_cv) / 0.6))
        if size_uniformity > 0.5:
            report.reasons.append(f"trade sizes unusually uniform (mean CV {mean_cv:.2f})")

    # --- signal 4: concentration -----------------------------------------
    # Volume dominated by a handful of hyperactive wallets.
    heavy_volume = sum(p.volume_usd for p in heavy)
    concentration = heavy_volume / total_volume
    if concentration > 0.7 and len(heavy) >= 3:
        report.reasons.append(
            f"{len(heavy)} hyperactive wallets account for {concentration:.0%} of volume"
        )

    score = (
        0.35 * uniformity
        + 0.25 * min(1.0, round_tripping)
        + 0.20 * size_uniformity
        + 0.20 * min(1.0, concentration)
    )
    report.wash_score = round(min(1.0, score), 4)
    report.signals = {
        "cohort_uniformity": round(uniformity, 4),
        "round_tripping": round(round_tripping, 4),
        "size_uniformity": round(size_uniformity, 4),
        "volume_concentration": round(concentration, 4),
        "n_heavy_wallets": float(len(heavy)),
    }

    suspects = cohort if len(cohort) >= 3 else [p for p in heavy if p.round_trip_ratio > 0.7]
    report.suspect_wallets = [p.wallet for p in suspects]
    report.suspect_volume_share = round(
        sum(p.volume_usd for p in suspects) / total_volume, 4
    ) if suspects else 0.0
    return report


# --------------------------------------------------------------------- smart money


@dataclass
class WalletScore:
    """Track record of one wallet across many tokens."""

    wallet: str
    n_tokens: int
    n_wins: int
    win_rate: float
    mean_forward_return: float
    confidence_low: float      # lower bound of the win-rate interval
    score: float               # 0..1, shrunk toward the base rate
    verdict: str

    @property
    def is_smart(self) -> bool:
        return self.verdict == "smart"


def score_wallets(
    entries: dict[str, list[tuple[str, float]]],
    *,
    base_rate: float,
    min_tokens: int = 8,
    z: float = 1.96,
) -> list[WalletScore]:
    """Rank wallets by forward performance of the tokens they bought.

    ``entries`` maps wallet → list of (token, forward_return) for each first
    entry that wallet made.

    Two corrections keep this honest. **Shrinkage**: a wallet with 3 wins from 3
    tokens is not better than one with 60 wins from 100; the estimate is pulled
    toward the population base rate in proportion to how little evidence there
    is. **Interval, not point estimate**: the Wilson lower bound is reported, so
    a wallet only ranks highly when its record is both good *and* long enough to
    believe.
    """
    scores: list[WalletScore] = []
    for wallet, records in entries.items():
        n = len(records)
        if n < min_tokens:
            continue
        rets = [r for _, r in records]
        wins = sum(1 for r in rets if r > 0)
        raw_rate = wins / n

        # Wilson score interval lower bound — well-behaved for small samples.
        denom = 1.0 + z * z / n
        centre = (raw_rate + z * z / (2 * n)) / denom
        margin = (z * math.sqrt(raw_rate * (1 - raw_rate) / n + z * z / (4 * n * n))) / denom
        lower = max(0.0, centre - margin)

        # Empirical-Bayes style shrinkage toward the base rate.
        prior_weight = float(min_tokens)
        shrunk = (wins + base_rate * prior_weight) / (n + prior_weight)

        if lower > base_rate * 1.25 and n >= min_tokens * 2:
            verdict = "smart"
        elif lower > base_rate:
            verdict = "promising"
        elif raw_rate < base_rate * 0.5:
            verdict = "avoid"
        else:
            verdict = "neutral"

        scores.append(
            WalletScore(
                wallet=wallet, n_tokens=n, n_wins=wins, win_rate=round(raw_rate, 4),
                mean_forward_return=round(statistics.fmean(rets), 4),
                confidence_low=round(lower, 4), score=round(shrunk, 4), verdict=verdict,
            )
        )
    # Rank by the shrunk score rather than the raw Wilson bound. Wilson is
    # correct for a single wallet in isolation, but we are selecting from
    # thousands: with that many candidates, some will post a short perfect
    # record by chance alone, and Wilson rates 8-from-8 above 45-from-60.
    # Shrinkage toward the base rate penalises exactly that, so it is the
    # appropriate key when the dominant risk is selection bias.
    scores.sort(key=lambda s: (s.score, s.n_tokens), reverse=True)
    return scores


def early_buyer_quality(
    trades: Sequence[Any], smart_wallets: set[str], first_n: int = 50
) -> dict[str, float]:
    """Share of a token's earliest buyers that are known-good wallets."""
    buys = sorted([t for t in trades if str(_get(t, "kind", "")) == "buy"], key=_ts)[:first_n]
    if not buys:
        return {"early_smart_share": 0.0, "early_smart_count": 0.0, "n_early_buyers": 0.0}
    wallets = {_get(t, "wallet", "") for t in buys}
    wallets.discard("")
    hits = wallets & smart_wallets
    return {
        "early_smart_share": len(hits) / max(len(wallets), 1),
        "early_smart_count": float(len(hits)),
        "n_early_buyers": float(len(wallets)),
    }


def _get(t: Any, key: str, default: Any = None) -> Any:
    if hasattr(t, "keys"):
        try:
            return t[key]
        except (KeyError, IndexError):
            return default
    return getattr(t, key, default)


def _ts(t: Any) -> int:
    value = _get(t, "ts", None)
    if value is None:
        value = _get(t, "timestamp", 0)
    if isinstance(value, str):
        try:
            return int(datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp())
        except ValueError:
            return 0
    if isinstance(value, datetime):
        return int(value.timestamp())
    return int(value or 0)
